// packages/iview/src/components/select/select.vue
<script>
import {toDefSlot} from '@form-create/utils';

export default {
    name: 'fc-select',
    functional: true,
    props: {
        options: {
            type: Array,
            default: () => ([])
        },
    },
    render(h, ctx) {
        return <Select {...ctx.data}>{ctx.props.options.map((props, index) => {

            const slot = props.slot ? toDefSlot(props.slot, h) : [];

            return <Option {...{props}}
                key={`t${index}${ctx._uid}`}>{slot}</Option>
        }).concat(ctx.chlidren)}</Select>;
    }
}
</script>

// packages/element-ui/src/components/select/index.jsx
import {toDefSlot} from '@form-create/utils';

export default {
    name: 'fc-elm-select',
    functional: true,
    props: {
        options: {
            type: Array,
            default: () => ([])
        },
    },
    render(h, ctx) {
        return <ElSelect {...ctx.data}>{ctx.props.options.map((props, index) => {

            const slot = props.slot ? toDefSlot(props.slot, h) : [];

            return <ElOption {...{props}}
                key={`t${index}${ctx._uid}`}>{slot}</ElOption>
        }).concat(ctx.chlidren)}</ElSelect>;
    }
}
