// packages/ant-design/src/components/upload/index.jsx
import {hasSlot, toArray, toString} from '@form-create/utils';

const parseFile = function (file, uid) {
        return {
            url: file,
            name: getFileName(file),
            status: 'done',
            uid: uid + 1
        };
    }, getFileName = function (file) {
        return toString(file).split('/').pop()
    }, parseUpload = function (file) {
        return {url: file.url, file};
    };


export default {
    name: 'fc-antd-update',
    props: {
        limit: {
            type: Number,
            default: 0
        },
        ctx: {
            type: Object,
            default: () => ({props: {}})
        },
        children: {
            type: Array,
            default: () => []
        },
        value: {
            type: [Array, String],
            default: () => []
        },
        onSuccess: {
            type: Function,
            required: true
        }
    },
    data() {
        const fileList = toArray(this.value).map(parseFile);
        return {
            defaultUploadList: fileList,
            previewImage: '',
            previewVisible: false,
            uploadList: fileList.map(parseUpload)
        };
    },
    watch: {
        value(n) {
            const fileList = toArray(n).map(parseFile);
            this.$refs.upload.sFileList = fileList;
            this.uploadList = fileList.map(parseUpload)
        }
    },
    methods: {
        initChildren() {
            if (!hasSlot(this.children, 'default'))
                this.children.push(this.makeBtn())
        },
        makeBtn() {
            return <div>
                <AIcon type="plus"/>
            </div>
        },
        handlePreview(file) {
            this.previewImage = file.url;
            this.previewVisible = true;
        },
        handleCancel() {
            this.previewVisible = false;
        },
        handleChange({file, fileList}) {
            const list = this.uploadList;
            if (file.status === 'done') {
                this.onSuccess(file, fileList);
                if (file.url) list.push({
                    url: file.url,
                    file: fileList[fileList.length - 1]
                });
                this.input();
            } else if (file.status === 'removed') {
                list.forEach((v, i) => {
                    if (v.file === file) {
                        list.splice(i, 1);
                    }
                });
                this.input();
            }
        },
        input() {
            this.$emit('input', this.uploadList.map(v => v.url));
        },

    },
    render() {
        this.initChildren();
        return <div>
            <AUpload {...this.ctx} on-preview={this.handlePreview} on-change={this.handleChange}
                ref="upload" defaultFileList={this.defaultUploadList}>{this.children}</AUpload>
            <aModal visible={this.previewVisible} footer={null} on-cancel={this.handleCancel}>
                <img style="width: 100%" src={this.previewImage}/>
            </aModal>
        </div>;
    }
}

// packages/iview/src/components/upload/upload.vue
<script>
import {iviewConfig} from '../../core/config';
import {hasSlot, toArray, toString} from '@form-create/utils';
import {defaultOnHandle} from '../../core/modal';
import style from '../../style/index.css';

function parseFile(file) {
    return {
        url: file,
        name: getFileName(file)
    };
}

function getFileName(file) {
    return toString(file).split('/').pop()
}


export default {
    name: 'fc-upload',

    props: {
        ctx: {
            type: Object,
            default: () => ({props: {}})
        },
        children: {
            type: Array,
            default: () => ([])
        },
        onHandle: {
            type: Function,
            default(file) {
                defaultOnHandle(file.url, this.modalTitle)
            }
        },
        uploadType: {
            type: String,
            default: 'file'
        },
        maxLength: {
            type: Number,
            default: 0
        },
        allowRemove: {
            type: Boolean,
            default: true
        },
        modalTitle: {
            type: String,
            default: '预览'
        },
        handleIcon: [String, Boolean],
        value: [Array, String]
    },
    data() {
        return {
            uploadList: []
        }
    },
    created() {
        if (this.ctx.props.showUploadList === undefined)
            this.ctx.props.showUploadList = false;
        this.ctx.props.defaultFileList = toArray(this.value).map(parseFile);
    },
    watch: {
        value(n) {
            this.$refs.upload.fileList = toArray(n).map(parseFile);
            this.uploadList = this.$refs.upload.fileList;
        },
        maxLength(n, o) {
            if (o === 1 || n === 1)
                this.update();
        }
    },
    methods: {
        isDisabled() {
            return this.ctx.props.disabled === true;
        },
        onRemove(file) {
            if (this.isDisabled()) return;
            this.$refs.upload.handleRemove(file);
        },
        handleClick(file) {
            if (this.isDisabled()) return;
            this.onHandle(file);
        },

        makeDefaultBtn() {
            return <div class={style['fc-upload-btn']}>
                <icon props={{
                    type: this.uploadType === 'file' ? 'ios-cloud-upload-outline' : iviewConfig.imgUpIcon,
                    size: 20
                }}/>
            </div>
        },
        makeItem(file) {
            return this.uploadType === 'image'
                ? <img src={file.url}/>
                : <icon props={{type: iviewConfig.fileIcon, size: 40}}/>
        },
        makeRemoveIcon(file) {
            return <icon type='ios-trash-outline' on-click={() => this.onRemove(file)}/>;
        },
        makeHandleIcon(file) {
            return <icon type={this.handleIcon === true ? 'ios-eye-outline' : this.handleIcon}
                on-click={() => this.handleClick(file)}/>;
        },
        makeProgress(file) {
            return <Progress props={{percent: file.percentage, hideInfo: true}} style="width:90%"/>
        },
        makeIcons(file) {
            const icons = [];
            if (this.allowRemove || this.handleIcon) {
                if (this.handleIcon)
                    icons.push(this.makeHandleIcon(file));
                if (this.allowRemove)
                    icons.push(this.makeRemoveIcon(file));

                return <div class={style['fc-upload-cover']}>{icons}</div>;
            }
        },

        makeFiles() {
            return this.uploadList.map(file => <div
                class={style['fc-files']}>{file.showProgress ? this.makeProgress(file) : [this.makeItem(file), this.makeIcons(file)]}</div>);
        },
        makeUpload() {
            return <Upload ref="upload"
                style={{display: 'inline-block'}} {...this.ctx}>{this.children}</Upload>;
        },
        initChildren() {
            if (!hasSlot(this.children, 'default'))
                this.children.push(this.makeDefaultBtn());
        },
        update() {
            let files = this.$refs.upload.fileList.map((file) => file.url).filter((url) => url !== undefined);
            this.$emit('input', this.maxLength === 1 ? (files[0] || '') : files);
        }
    },
    render() {
        const isShow = (!this.maxLength || this.maxLength > this.uploadList.length);

        if (this.$refs.upload) {
            if (this.ctx.props.showUploadList === undefined)
                this.ctx.props.showUploadList = this.$refs.upload.showUploadList;
            this.ctx.props.defaultFileList = this.$refs.upload.defaultFileList;
        }

        this.initChildren();

        return (
            <div class={{
                [style['fc-upload']]: true,
                [style['fc-hide-btn']]: !isShow
            }}>{[this.ctx.props.showUploadList ? [] : this.makeFiles(), this.makeUpload()]}</div>);
    },
    mounted() {
        this.uploadList = this.$refs.upload.fileList;
        this.$watch(() => this.$refs.upload.fileList, () => {
            this.update();
        }, {deep: true});
    }
}
</script>
