// packages/iview/src/components/checkbox/index.jsx
export default {
    name: 'fc-checkbox',
    props: {
        options: {
            type: Array,
            default: () => []
        },
        children: {
            type: Array,
            default: () => []
        },
        ctx: {
            type: Object,
            default: () => ({})
        },
        value: {
            type: Array,
            default: () => []
        },
    },
    watch: {
        value() {
            this.update();
        }
    },
    data() {
        return {
            trueValue: []
        }
    },
    methods: {
        onInput(n) {
            this.$emit('input', this.options.filter((opt) => n.indexOf(opt.label) !== -1).map((opt) => opt.value));
        },
        update() {
            this.trueValue = this.options.filter((opt) => this.value.indexOf(opt.value) !== -1)
                .map((option) => option.label)
        }
    },
    created() {
        this.update();
    },
    render() {
        return <CheckboxGroup {...this.ctx} v-model={this.trueValue}
            on-input={this.onInput}>{this.options.map(opt => {
                const props = {...opt};
                delete props.value;
                return <Checkbox {...{props}}/>
            }).concat(this.chlidren)}</CheckboxGroup>
    }
}

// packages/vant/src/components/checkbox.jsx
import {defineComponent, toRef} from 'vue';

const NAME = 'fcCheckbox';

export default defineComponent({
    name: NAME,
    inheritAttrs: false,
    props: {
        value: Array,
        options: Array,
    },
    emits: ['input'],
    setup(props, _) {
        const modelValue = toRef(props, 'value', []);
        const options = toRef(props, 'options');

        return {
            options,
            modelValue,
            onInput(val) {
                _.emit('input', val);
            },
        }
    },
    render() {
        return <van-checkbox-group direction="horizontal" {...this.$attrs}
                                   value={Array.isArray(this.modelValue) ? this.modelValue : []}
                                   onInput={this.onInput}>
            {(this.options || []).map(opt => {
                const tmp = {...opt};
                const {text, value} = opt;
                delete tmp.text;
                delete tmp.value;
                return <van-checkbox name={value} shape="square" {...tmp}>{text || opt.label || value}</van-checkbox>
            })}
        </van-checkbox-group>
    }
});
