// packages/iview/src/components/radio/radio.vue
<script>
export default {
    name: 'fc-radio',
    functional: true,
    props: {
        options: {
            type: Array,
            default: () => ([])
        },
    },
    render(h, ctx) {
        return <RadioGroup {...ctx.data}>{ctx.props.options.map(opt => {
            const props = {...opt};
            delete props.value;
            return <Radio {...{props}}/>
        }).concat(ctx.chlidren)}</RadioGroup>
    }
}
</script>

// packages/element-ui/src/components/radio/index.jsx
export default {
    name: 'fc-elm-radio',
    functional: true,
    props: {
        options: {
            type: Array,
            default: () => ([])
        },
        type: String
    },
    render(h, ctx) {
        return <ElRadioGroup {...ctx.data}>{ctx.props.options.map(opt => {
            const props = {...opt};
            delete props.value;
            return ctx.props.type === 'button' ? <ElRadioButton {...{props}}/> : <ElRadio {...{props}}/>;
        }).concat(ctx.chlidren)}</ElRadioGroup>
    }
}
