// packages/iview/src/components/tree/tree.vue
<script>
import {toArray} from '@form-create/utils';


export default {
    name: 'fc-tree',
    props: {
        ctx: {
            type: Object,
            default: () => ({props: {}})
        },
        children: {
            type: Array,
            default: () => ([])
        },
        type: {
            type: String,
            default: 'checked'
        },
        value: {
            type: Array,
            default: () => ([])
        }
    },
    data() {
        return {
            treeData: []
        }
    },
    watch: {
        value(n) {
            n = toArray(n);
            const data = this.$refs.tree.data;
            this.type === 'selected' ? this.selected(data, n) : this.checked(data, n);
        }
    },
    methods: {
        selected(_data, value) {
            _data.forEach((node) => {
                this.$set(node, 'selected', value.indexOf(node.id) !== -1);
                if (node.children !== undefined && Array.isArray(node.children))
                    this.selected(node.children, value);
            });
        },
        checked(_data, value) {
            _data.forEach((node) => {
                if (value.indexOf(node.id) !== -1)
                    this.$set(node, 'checked', true);
                else {
                    this.$set(node, 'indeterminate', false);
                    this.$set(node, 'checked', false);
                }
                if (node.children !== undefined && Array.isArray(node.children))
                    this.checked(node.children, value);
            });
        },
        makeTree() {
            return <Tree ref="tree" {...this.ctx}>{this.children}</Tree>;
        },
        updateTreeData() {
            const type = (this.type).toLocaleLowerCase();

            if (type === 'selected')
                this.treeData = this.$refs.tree.getSelectedNodes();
            else if (type === 'indeterminate')
                this.treeData = this.$refs.tree.getCheckedAndIndeterminateNodes();
            else
                this.treeData = this.$refs.tree.getCheckedNodes();
            this.$emit('input', this.treeData.map(node => node.id));
        }
    },
    render() {
        return (<div>{this.makeTree()}</div>);
    },
    mounted() {
        this.$nextTick(() => {
            this.$watch(() => this.$refs.tree.flatState, () => this.updateTreeData())
        })

    }
}
</script>

// packages/element-ui/src/components/tree/index.jsx
import {toArray} from '@form-create/utils';


export default {
    name: 'fc-elm-tree',
    props: {
        ctx: {
            type: Object,
            default: () => ({props: {}})
        },
        children: {
            type: Array,
            default: () => ([])
        },
        type: {
            type: String,
            default: 'checked'
        },
        value: {
            type: [Array, String, Number],
            default: () => ([])
        }
    },
    watch: {
        value() {
            this.setValue();
        }
    },
    methods: {
        makeTree() {
            return <ElTree ref="tree" on-check-change={() => this.updateValue()}
                on-node-click={() => this.updateValue()} {...this.ctx}>{this.children}</ElTree>;
        },
        onChange() {
            this.updateValue()
        },

        updateValue() {
            const type = (this.type).toLocaleLowerCase();
            let value;

            if (type === 'selected')
                value = this.$refs.tree.getCurrentKey();
            else
                value = this.$refs.tree.getCheckedKeys();

            this.$emit('input', value);
        },
        setValue() {
            const type = (this.type).toLocaleLowerCase();

            if (type === 'selected')
                this.$refs.tree.setCurrentKey(this.value);
            else
                this.$refs.tree.setCheckedKeys(toArray(this.value));
        }
    },
    render() {
        return (<div>{this.makeTree()}</div>);
    },
    mounted() {
        this.setValue();
        this.updateValue();
    }
}
