// packages/iview/src/components/radio/index.jsx
export default {
    name: 'fc-radio',
    functional: true,
    props: {
        options: {
            type: Array,
            default: () => ([])
        },
    },
    render(h, ctx) {
        return <RadioGroup {...ctx.data}>{ctx.props.options.map(opt => {
            const props = {...opt};
            delete props.value;
            return <Radio {...{props}}/>
        }).concat(ctx.chlidren)}</RadioGroup>
    }
}

// packages/iview/src/components/radio/radio.vue
<script>
export default {
    name: 'fc-radio',
    functional: true,
    props: {
        options: {
            type: Array,
            default: () => ([])
        },
    },
    render(h, ctx) {
        return <RadioGroup {...ctx.data}>{ctx.props.options.map(opt => {
            const props = {...opt};
            delete props.value;
            return <Radio {...{props}}/>
        }).concat(ctx.chlidren)}</RadioGroup>
    }
}
</script>
