// packages/iview4/src/components/radio/index.jsx
import {uniqueId} from '@form-create/utils';

const NAME = 'fc-iview-radio';

export default {
    name: NAME,
    functional: true,
    props: {
        options: {
            type: Array,
            default: () => ([])
        },
        unique: {
            default: () => uniqueId()
        },
    },
    render(h, ctx) {
        return <RadioGroup {...ctx.data}>{ctx.props.options.map((opt, index) => {
            const props = {...opt};
            delete props.value;
            return <Radio {...{props}} key={NAME + index + ctx.props.unique}/>
        }).concat(ctx.chlidren)}</RadioGroup>
    }
}

// packages/iview/src/components/radio/radio.vue
<script>
export default {
    name: 'fc-radio',
    functional: true,
    props: {
        options: {
            type: Array,
            default: () => ([])
        },
    },
    render(h, ctx) {
        return <RadioGroup {...ctx.data}>{ctx.props.options.map(opt => {
            const props = {...opt};
            delete props.value;
            return <Radio {...{props}}/>
        }).concat(ctx.chlidren)}</RadioGroup>
    }
}
</script>
