// packages/iview4/src/components/select/index.jsx
import {toDefSlot, uniqueId} from '@form-create/utils';

const NAME = 'fc-iview-select';

export default {
    name: NAME,
    functional: true,
    props: {
        options: {
            type: Array,
            default: () => ([])
        },
        unique: {
            default: () => uniqueId()
        },
    },
    render(h, ctx) {
        return <Select {...ctx.data}>{ctx.props.options.map((props, index) => {

            const slot = props.slot ? toDefSlot(props.slot, h) : [];

            return <Option {...{props}}
                key={NAME + index + ctx.props.unique}>{slot}</Option>
        }).concat(ctx.chlidren)}</Select>;
    }
}

// packages/iview/src/components/select/select.vue
<script>
import {toDefSlot} from '@form-create/utils';

export default {
    name: 'fc-select',
    functional: true,
    props: {
        options: {
            type: Array,
            default: () => ([])
        },
    },
    render(h, ctx) {
        return <Select {...ctx.data}>{ctx.props.options.map((props, index) => {

            const slot = props.slot ? toDefSlot(props.slot, h) : [];

            return <Option {...{props}}
                key={`t${index}${ctx._uid}`}>{slot}</Option>
        }).concat(ctx.chlidren)}</Select>;
    }
}
</script>
